@echo off
echo Descargando ngrok manualmente...
powershell -Command "Invoke-WebRequest -Uri 'https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip' -OutFile 'ngrok.zip'"
echo Extrayendo ngrok...
powershell -Command "Expand-Archive -Path 'ngrok.zip' -DestinationPath '.'"
echo Iniciando ngrok...
ngrok http 3000
pause
